### ISSUE TITLE
Missing bracket in nginx config

### ISSUE THREAD

**Issue by n2x4** [2004gixxer600/openctihowto#1]
Thanks for putting this together, I was stepping through your docs and noticed that you're missing a closed bracket for your nginx config. Also, your Linkedin article is missing both in the code example. Just wanted to give you a heads up. The service fails to start without the brackets, but the error is pretty clear about the issue.

**Comment by 2004gixxer600** [comment]
Thanks. I’ll check it out. Sometimes copying and pasting goes awry. :)

Daniel Bender
FOR ALL SUPPORT REQUESTS
Phone - 315.652.0287
Email ***@***.***

________________________________
From: n2x4 ***@***.***>
Sent: Monday, July 3, 2023 9:10:27 PM
To: 2004gixxer600/openctihowto ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [2004gixxer600/openctihowto] Missing bracket in nginx config (Issue #1)


Thanks for putting this together, I was stepping through your docs and noticed that you're missing a closed bracket for your nginx config. Also, your Linkedin article is missing both in the code example. Just wanted to give you a heads up. The service fails to start without the brackets, but the error is pretty clear about the issue.

**Comment by 2004gixxer600** [comment]
All set!  Thank you Sir for pointing that out! 

You are the first person to ever tell me about that, I never caught it.  Like you said though, most people probably figured it out quickly when Nginx fails the syntax test with a self-descriptive code as you stated.
